### ISSUE TITLE
Invalid data found when processing output

### ISSUE THREAD

**Issue by berobloom** [brixt0n/tutk-ipcamera-proxy#1]
Hey,

I came across your repo and this is exactly what I needed for the camera I currently work on:
https://github.com/berobloom/LSCIndoorCameraLocal1080p

I have tried your example:

```
python3 tutk_ipcamera_proxy.py stream -t 5000 -d <UID> -u admin -p <password> -f /dev/stdout 2>stream.log | ffmpeg -i - -f rtsp -rtsp_transport tcp rtsp://localhost:8554/cam-office
```

But this results in a

```
 pipe:: Invalid data found when processing input
```

I used a Ubuntu 22.04 container in docker.

**Comment by brixt0n** [comment]
Hello, thanks for reaching out.

In your example, you need to update the UID to the ID of the device. If you do a `scan`action rather than `stream` you should be able to see the camera, if it's speaking the TUTK P2P protocol.

**Comment by berobloom** [comment]
Yes I already did that. Seems that the application does not always find the camera. After few retries I am able to stream to an MP4. Not yet to an rtsp.

It seems that audio is not yet working. Is there a flag I can set to enable.

If I remember correctly I could set a flag somewhere using a AVAPI_Client sample.

**Comment by brixt0n** [comment]
I've had this running for a year or so, without issue finding my cameras at least. Any ideas why it does not always find your camera? What camera model is this? I'm glad it at least works sometimes, gives a starting point for troubleshooting.

I never implemented the audio stream as I don't have a need (I'm grabbing the video frames). If you find time feel free to raise a PR!

**Comment by berobloom** [comment]
I see. Yes I believe this is something on my side that does not work correctly. The camera is a LSC Smart Connect 1080p. It is just a cheap tuya camera that has included a TUTK p2p server.

Aah I see, then I shall play around and try to get audio working. Thanks a lot! I could not find a lot of implementations regarding TUTK p2p. This one stands out :smile:  Cheers!
